[build-system]
requires = ["setuptools>=68.0.0", "wheel"]
build-backend = "setuptools.build_meta"

# Make changes here according to your repository
[project]
name = "DSA"
version = "1.2.0"
description = "Data Structure Practice"
authors = [
    { name = "Akhilesh Pratap Shahi", email = "akhileshpra.shahi@gmail.com" }
]
maintainers = [
    { name = "Akhilesh Pratap Shahi", email = "akhileshpra.shahi@gmail.com" }    
]


readme = "README.md"
dependencies = [
    "numpy>=2.0.0",
    "scikit-learn>=1.5.0",
    "pandas>=2.2.1",
    "networkx>=3.3",
    "matplotlib>=3.9.0",
]
keywords = ["DSA", "Data Structure", "Practice", "big-o", "complexity-analysis", "performance"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
requires-python = ">=3.8"

[tool.setuptools]
packages = [
    "DSA",
    "Ruler",
    "LearningCodes",
    "LearningCodes.LinkededList",
]
py-modules = ["Node"]

[tool.setuptools.package-dir]
"DSA" = "."
"Ruler" = "Ruler"
"LearningCodes" = "LearningCodes"
"LearningCodes.LinkededList" = "LearningCodes/LinkededList"
